// GENERATED by @vantis/data build — do not edit. Re-run: npx @vantis/data build
// This file must be within your tsconfig "include" paths to take effect.
export {};
declare module '@vantis/data' {
  interface Schema {
    posts: import('@vantis/data').InferRow<(typeof import("./schema.js"))["posts"]>;
    users: import('@vantis/data').InferRow<(typeof import("./schema.js"))["users"]>;
  }
}
